# -*- coding: utf-8 -*-
"""Data_loading_and_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1ifNCSgThtKiQSrcC-dH2ollJD282XO
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive/SST_Data"))

import xarray as xr
nc_path = "/content/drive/MyDrive/SST_Data/GISS-E2-1-H_historical_1850_2014.nc"
ds = xr.open_dataset(nc_path)
print(ds)

import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import detrend
from numpy.linalg import svd

nc_path = "/content/drive/MyDrive/SST_Data/GISS-E2-1-H_historical_1850_2014.nc"
ds = xr.open_dataset(nc_path)

sst = ds["sst"]

ensemble_id = 0

sst_ens = sst.isel(ensemble=ensemble_id)
sst_ens = sst_ens.fillna(0)
print(f"Using ensemble {ensemble_id}")

import os
print(os.listdir("/content/drive/MyDrive/SST_Data"))

nc_path = "/content/drive/MyDrive/SST_Data/GISS-E2-1-H_historical_1850_2014.nc"

nc_path = "/content/drive/MyDrive/SST_Data/GISS-E2-1-H_historical_1850_2014.nc"
ds = xr.open_dataset(nc_path)

ensemble_id = 0
sst = ds["sst"].isel(ensemble=ensemble_id)

import xarray as xr
import numpy as np
import torch
from scipy.signal import detrend
from torch.utils.data import Dataset, DataLoader


nc_path = "/content/drive/MyDrive/SST_Data/GISS-E2-1-H_historical_1850_2014.nc"
ds = xr.open_dataset(nc_path)

ensemble_id = 0
sst = ds["sst"].isel(ensemble=ensemble_id)

print("Original SST shape:", sst.shape)

# ==============================
# Train/Test split by years
# ==============================

train_years = slice(0,115)     # 1850–1965
test_years  = slice(115,None)  # 1966–2014

sst_train = sst.isel(years=train_years)
sst_test  = sst.isel(years=test_years)

print("Train years:", sst_train.shape)
print("Test years:", sst_test.shape)

# ==============================
# Computing climatology (TRAIN ONLY)
# ==============================

climatology = sst_train.mean(dim="years")

sst_train_anom = sst_train - climatology
sst_test_anom  = sst_test  - climatology

# ==============================
# Removing linear trend
# ==============================

sst_train_dt = xr.apply_ufunc(
    detrend,
    sst_train_anom.fillna(0),
    input_core_dims=[["years"]],
    output_core_dims=[["years"]],
    kwargs={"type": "linear"},
    vectorize=True,
    dask="parallelized",
    output_dtypes=[sst_train_anom.dtype],
)

sst_test_dt = xr.apply_ufunc(
    detrend,
    sst_test_anom.fillna(0),
    input_core_dims=[["years"]],
    output_core_dims=[["years"]],
    kwargs={"type": "linear"},
    vectorize=True,
    dask="parallelized",
    output_dtypes=[sst_test_anom.dtype],
)

# ==============================
# Converting (years,mon,lat,lon) -> (time,lat,lon)
# ==============================

train_time = (
    sst_train_dt
    .stack(time=("years","mon"))
    .transpose("time","lat","lon")
)

test_time = (
    sst_test_dt
    .stack(time=("years","mon"))
    .transpose("time","lat","lon")
)

train_time = train_time.fillna(0.0)
test_time  = test_time.fillna(0.0)

print("Train time shape:", train_time.shape)
print("Test time shape:", test_time.shape)

train_mean = train_time.mean()
train_std  = train_time.std()

train_norm = (train_time - train_mean) / train_std
test_norm  = (test_time  - train_mean) / train_std

train_data = train_norm.values
test_data_full = test_norm.values

print("Train samples:", train_data.shape)
print("Full test samples:", test_data_full.shape)

# ==============================
# Validation/Test split (300 / 300)
# ==============================

val_data  = test_data_full[:300]
test_data = test_data_full[300:600]

print("Train:", train_data.shape)
print("Val:", val_data.shape)
print("Test:", test_data.shape)

class SSTVAEDataset(Dataset):

    def __init__(self,data):
        self.data = torch.tensor(data,dtype=torch.float32).unsqueeze(1)

    def __len__(self):
        return self.data.shape[0]

    def __getitem__(self,idx):
        x = self.data[idx]
        return x,x


train_dataset = SSTVAEDataset(train_data)
val_dataset   = SSTVAEDataset(val_data)
test_dataset  = SSTVAEDataset(test_data)

batch_size = 16

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    drop_last=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

print("Dataloaders created successfully.")